# Generated by Django 3.2.20 on 2023-09-05 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("geonode_themes", "0014_auto_20220214_0910"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=250, verbose_name="Site name")),
                (
                    "theme",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="geonode_themes.geonodethemecustomization",
                    ),
                ),
            ],
        ),
    ]
