# Generated by Django 3.2.20 on 2023-09-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0034_auto_20200512_1431"),
        ("subsites", "0003_auto_20230907_1617"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsite",
            name="groups",
            field=models.ManyToManyField(
                blank=True, default=None, null=True, to="groups.GroupProfile"
            ),
        ),
        migrations.AlterField(
            model_name="subsite",
            name="slug",
            field=models.SlugField(
                help_text="Sub site name, formatted as slug. This slug is going to be used as path for access the subsite",
                max_length=250,
                verbose_name="Site name",
            ),
        ),
    ]
