# Generated by Django 3.2.20 on 2023-09-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('subsites', '0006_auto_20230911_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsite',
            name='resource_type',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='contenttypes.ContentType'),
        ),
    ]
