# Generated by Django 3.2.20 on 2023-09-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsites', '0007_alter_subsite_resource_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsite',
            name='resource_type',
        ),
        migrations.AddField(
            model_name='subsite',
            name='resource_type',
            field=models.CharField(blank=True, choices=[('document', 'document'), ('map', 'map'), ('dataset', 'dataset'), ('dashboard', 'dashboard'), ('geoapp', 'geoapp'), ('geostory', 'geostory')], default=None, max_length=100, null=True),
        ),
    ]
