# Generated by Django 3.2.21 on 2023-10-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsites', '0007_alter_subsite_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsite',
            name='resource_type',
        ),
        migrations.AddField(
            model_name='subsite',
            name='types',
            field=models.JSONField(blank=True, default=list, max_length=100, null=True),
        ),
    ]
