# Generated by Django 3.2.21 on 2023-10-06 08:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subsites", "0007_alter_subsite_theme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subsite",
            name="resource_type",
        ),
        migrations.AddField(
            model_name="subsite",
            name="types",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=30),
                blank=True,
                default=list,
                max_length=100,
                null=True,
                size=None,
            ),
        ),
    ]
