# Generated by Django 3.2.21 on 2023-10-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsites', '0008_auto_20231005_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsite',
            name='types',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
