# Generated by Django 3.2.22 on 2023-10-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsites', '0009_subsite_allowed_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsite',
            name='description',
            field=models.TextField(blank=True, verbose_name='Subsite description'),
        ),
        migrations.AddField(
            model_name='subsite',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='img/%Y/%m'),
        ),
    ]
