# Generated by Django 3.2.22 on 2023-12-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsites', '0010_auto_20231027_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsite',
            name='can_add_resource',
            field=models.BooleanField(default=False, help_text='If TRUE, the users belonging to the contributors group will be able to add new resources in the subsite', verbose_name='Contributors can add resources'),
        ),
    ]
